use empresa_prueba_ud3; 
-- Tabla ACC_MOVEMENT
CREATE TABLE IF NOT EXISTS `ACC_MOVEMENT` (
  `ACCOUNT_MOV_ID` INT AUTO_INCREMENT NOT NULL,
  `ACCOUNT_ORIGIN_ID` INT NOT NULL,
  `ACCOUNT_DEST_ID` INT NOT NULL,
  `AMOUNT` DECIMAL(19,4) NOT NULL,
  `DATETIME` DATETIME NOT NULL,
  PRIMARY KEY (`ACCOUNT_MOV_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla ACCOUNT
CREATE TABLE IF NOT EXISTS `ACCOUNT` (
  `ACCOUNTNO` INT AUTO_INCREMENT NOT NULL,
  `AMOUNT` DECIMAL(19,4) NOT NULL,
  PRIMARY KEY (`ACCOUNTNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla DEPARTMENT
CREATE TABLE IF NOT EXISTS `DEPARTMENT` (
  `DEPTNO` INT AUTO_INCREMENT NOT NULL,
  `DNAME` VARCHAR(20) DEFAULT NULL,
  `LOC` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`DEPTNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla EMPLOYEE
CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
  `EMPLOYEENO` INT AUTO_INCREMENT NOT NULL,
  `ENAME` VARCHAR(20) DEFAULT NULL,
  `JOB` VARCHAR(20) DEFAULT NULL,
  `MGR` INT DEFAULT NULL,
  `HIREDATE` DATE DEFAULT NULL,
  `SAL` DECIMAL(19,4) DEFAULT NULL,
  `COMM` DECIMAL(19,4) DEFAULT NULL,
  `DEPARTMENTNO` INT DEFAULT NULL,
  PRIMARY KEY (`EMPLOYEENO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla EMPLOYEE_ACCOUNT
CREATE TABLE IF NOT EXISTS `EMPLOYEE_ACCOUNT` (
  `EMPLOYEENO` INT NOT NULL,
  `ACCOUNTNO` INT NOT NULL,
  PRIMARY KEY (`EMPLOYEENO`, `ACCOUNTNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
