USE empresa_prueba_ud3;

-- Crear la clave foránea para `ACCOUNT_DEST_ID` en la tabla `ACC_MOVEMENT`
ALTER TABLE ACC_MOVEMENT 
ADD CONSTRAINT FK_ACC_MOVEMENT_ACCOUNT_DEST 
FOREIGN KEY (ACCOUNT_DEST_ID) 
REFERENCES ACCOUNT (ACCOUNTNO);

-- Crear la clave foránea para `ACCOUNT_ORIGIN_ID` en la tabla `ACC_MOVEMENT`
ALTER TABLE ACC_MOVEMENT 
ADD CONSTRAINT FK_ACC_MOVEMENT_ACCOUNT_ORIGIN 
FOREIGN KEY (ACCOUNT_ORIGIN_ID) 
REFERENCES ACCOUNT (ACCOUNTNO);

-- Crear la clave foránea para `DEPARTMENTNO` en la tabla `EMPLOYEE`
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT 
FOREIGN KEY (DEPARTMENTNO) 
REFERENCES DEPARTMENT (DEPTNO);

-- Crear la clave foránea para `MGR` en la tabla `EMPLOYEE` (haciendo referencia a la misma tabla EMPLOYEE)
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_EMPLOYEE_MGR 
FOREIGN KEY (MGR) 
REFERENCES EMPLOYEE (EMPLOYEENO);

-- Crear la clave foránea para `ACCOUNTNO` en la tabla `EMPLOYEE_ACCOUNT`
ALTER TABLE EMPLOYEE_ACCOUNT 
ADD CONSTRAINT FK_EMPLOYEE_ACCOUNT_ACCOUNT 
FOREIGN KEY (ACCOUNTNO) 
REFERENCES ACCOUNT (ACCOUNTNO);

-- Crear la clave foránea para `EMPLOYEENO` en la tabla `EMPLOYEE_ACCOUNT`
ALTER TABLE EMPLOYEE_ACCOUNT 
ADD CONSTRAINT FK_EMPLOYEE_ACCOUNT_EMPLOYEE 
FOREIGN KEY (EMPLOYEENO) 
REFERENCES EMPLOYEE (EMPLOYEENO);
