package com.example.hibernate.model;
// Generated 13 mar 2025, 20:02:05 by Hibernate Tools 6.6.0.Final


import static jakarta.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * AccMovement generated by hbm2java
 */
@Entity
@Table(name="acc_movement"
)
public class AccMovement  implements java.io.Serializable {


     private Integer accountMovId;
     private Account accountDestino;
     private Account accountOrigen;
     private BigDecimal amount;
     private LocalDateTime datetime;

    public AccMovement() {
    }

    public AccMovement(Account accountByAccountDestId,
            Account accountByAccountOriginId, BigDecimal amount,
                     LocalDateTime datetime) {
       this.accountDestino = accountByAccountDestId;
       this.accountOrigen = accountByAccountOriginId;
       this.amount = amount;
       this.datetime = datetime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ACCOUNT_MOV_ID", unique=true, nullable=false)
    public Integer getAccountMovId() {
        return this.accountMovId;
    }
    
    public void setAccountMovId(Integer accountMovId) {
        this.accountMovId = accountMovId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_DEST_ID", nullable=false)
    public Account getAccountDestino() {
        return this.accountDestino;
    }
    
    public void setAccountDestino(Account accountByAccountDestId) {
        this.accountDestino = accountByAccountDestId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_ORIGIN_ID", nullable=false)
    public Account getAccountOrigen() {
        return this.accountOrigen;
    }
    
    public void setAccountOrigen(Account accountByAccountOriginId) {
        this.accountOrigen = accountByAccountOriginId;
    }

    
    @Column(name="AMOUNT", nullable=false, precision=19, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

  
    @Column(name="DATETIME", nullable=false, length=19)
    public LocalDateTime getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(LocalDateTime datetime) {
        this.datetime = datetime;
    }




}


