package com.example.hibernate.model;
// Generated 20 feb 2025, 18:07:51 by Hibernate Tools 6.6.0.Final


import static jakarta.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * AccMovement generated by hbm2java
 */
@Entity
@Table(name="acc_movement"
)
public class AccMovement  implements java.io.Serializable {


     private Integer accountMovId;
     private Account accountByAccountDestId;
     private Account accountByAccountOriginId;
     private BigDecimal amount;
     private Instant datetime;

    public AccMovement() {
    }

    public AccMovement(Account accountByAccountDestId, Account accountByAccountOriginId, BigDecimal amount, Instant datetime) {
       this.accountByAccountDestId = accountByAccountDestId;
       this.accountByAccountOriginId = accountByAccountOriginId;
       this.amount = amount;
       this.datetime = datetime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ACCOUNT_MOV_ID", unique=true, nullable=false)
    public Integer getAccountMovId() {
        return this.accountMovId;
    }
    
    public void setAccountMovId(Integer accountMovId) {
        this.accountMovId = accountMovId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_DEST_ID", nullable=false)
    public Account getAccountByAccountDestId() {
        return this.accountByAccountDestId;
    }
    
    public void setAccountByAccountDestId(Account accountByAccountDestId) {
        this.accountByAccountDestId = accountByAccountDestId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_ORIGIN_ID", nullable=false)
    public Account getAccountByAccountOriginId() {
        return this.accountByAccountOriginId;
    }
    
    public void setAccountByAccountOriginId(Account accountByAccountOriginId) {
        this.accountByAccountOriginId = accountByAccountOriginId;
    }

    
    @Column(name="AMOUNT", nullable=false, precision=19, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    //@Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATETIME", nullable=false, length=19)
    public Instant getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Instant datetime) {
        this.datetime = datetime;
    }

    @Override
    public String toString() {
        return "AccMovement [accountMovId=" + accountMovId + ", amount=" + amount + ", datetime=" + datetime + "]";
    }




}


