package com.example.hibernate.model;
// Generated 20 feb 2025, 18:07:51 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
)
public class Account  implements java.io.Serializable {


     private Integer accountno;
     private Emp emp;
     private BigDecimal amount;
     private Set<AccMovement> accMovementsForAccountDestId = new HashSet<AccMovement>(0);
     private Set<AccMovement> accMovementsForAccountOriginId = new HashSet<AccMovement>(0);

    public Account() {
    }

	
    public Account(Emp emp, BigDecimal amount) {
        this.emp = emp;
        this.amount = amount;
    }
    public Account(Emp emp, BigDecimal amount, Set<AccMovement> accMovementsForAccountDestId, Set<AccMovement> accMovementsForAccountOriginId) {
       this.emp = emp;
       this.amount = amount;
       this.accMovementsForAccountDestId = accMovementsForAccountDestId;
       this.accMovementsForAccountOriginId = accMovementsForAccountOriginId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ACCOUNTNO", unique=true, nullable=false)
    public Integer getAccountno() {
        return this.accountno;
    }
    
    public void setAccountno(Integer accountno) {
        this.accountno = accountno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPNO", nullable=false)
    public Emp getEmp() {
        return this.emp;
    }
    
    public void setEmp(Emp emp) {
        this.emp = emp;
    }

    
    @Column(name="AMOUNT", nullable=false, precision=19, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accountByAccountDestId")
    public Set<AccMovement> getAccMovementsForAccountDestId() {
        return this.accMovementsForAccountDestId;
    }
    
    public void setAccMovementsForAccountDestId(Set<AccMovement> accMovementsForAccountDestId) {
        this.accMovementsForAccountDestId = accMovementsForAccountDestId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accountByAccountOriginId")
    public Set<AccMovement> getAccMovementsForAccountOriginId() {
        return this.accMovementsForAccountOriginId;
    }
    
    public void setAccMovementsForAccountOriginId(Set<AccMovement> accMovementsForAccountOriginId) {
        this.accMovementsForAccountOriginId = accMovementsForAccountOriginId;
    }




}


