package com.example.hibernate.model;
// Generated 13 mar 2025, 20:02:05 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
)
public class Account  implements java.io.Serializable {


     private Integer accountno;
     private BigDecimal amount;
     private Set<Employee> employees = new HashSet<Employee>(0);
     private Set<AccMovement> accMovementsForAccountDestId = new HashSet<AccMovement>(0);
     private Set<AccMovement> accMovementsForAccountOriginId = new HashSet<AccMovement>(0);

    public Account() {
    }

	
    public Account(BigDecimal amount) {
        this.amount = amount;
    }
    public Account(BigDecimal amount, Set<Employee> employees, Set<AccMovement> accMovementsForAccountDestId, Set<AccMovement> accMovementsForAccountOriginId) {
       this.amount = amount;
       this.employees = employees;
       this.accMovementsForAccountDestId = accMovementsForAccountDestId;
       this.accMovementsForAccountOriginId = accMovementsForAccountOriginId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ACCOUNTNO", unique=true, nullable=false)
    public Integer getAccountno() {
        return this.accountno;
    }
    
    public void setAccountno(Integer accountno) {
        this.accountno = accountno;
    }

    
    @Column(name="AMOUNT", nullable=false, precision=19, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="accounts")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accountByAccountDestId")
    public Set<AccMovement> getAccMovementsForAccountDestId() {
        return this.accMovementsForAccountDestId;
    }
    
    public void setAccMovementsForAccountDestId(Set<AccMovement> accMovementsForAccountDestId) {
        this.accMovementsForAccountDestId = accMovementsForAccountDestId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accountByAccountOriginId")
    public Set<AccMovement> getAccMovementsForAccountOriginId() {
        return this.accMovementsForAccountOriginId;
    }
    
    public void setAccMovementsForAccountOriginId(Set<AccMovement> accMovementsForAccountOriginId) {
        this.accMovementsForAccountOriginId = accMovementsForAccountOriginId;
    }




}


