package com.example.hibernate.model;
// Generated 5 jun 2025, 5:59:52 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Authors generated by hbm2java
 */
@Entity
@Table(name="authors"
)
public class Author  implements java.io.Serializable {


     private Integer authorId;
     private String firstName;
     private String middleName;
     private String lastName;
     private Date birthDate;
     private Set<Book> books = new HashSet<Book>(0);

    public Author() {
    }

	
    public Author(String firstName) {
        this.firstName = firstName;
    }
    public Author(String firstName, String middleName, String lastName, Date birthDate, Set<Book> bookses) {
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.birthDate = birthDate;
       this.books = bookses;
    }
   
     public Author(String firstName, String middleName, String lastName) {
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
    }


     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="author_id", unique=true, nullable=false)
    public Integer getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    
    @Column(name="first_name", nullable=false, length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="middle_name", length=50)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="last_name", length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birth_date", length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="authors")
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> bookses) {
        this.books = bookses;
    }


    @Override
    public String toString() {
        return "Author [authorId=" + authorId + ", firstName=" + firstName + ", middleName=" + middleName
                + ", lastName=" + lastName + ", birthDate=" + birthDate + "]";
    }




}


