package com.example.hibernate.model;
// Generated 5 jun 2025, 5:59:52 by Hibernate Tools 6.6.0.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
@Entity
@Table(name = "books")
public class Book implements java.io.Serializable {

    private Integer bookId;
    private Publisher publisher;
    private String title;
    private String isbn;
    private Date publishedDate;
    private Set<Author> authors = new HashSet<Author>(0);

    public Book() {
    }

    public Book(String title) {
        this.title = title;
    }

    public Book(Publisher publishers, String title, String isbn, Date publishedDate, Set<Author> authorses) {
        this.publisher = publishers;
        this.title = title;
        this.isbn = isbn;
        this.publishedDate = publishedDate;
        this.authors = authorses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "book_id", unique = true, nullable = false)
    public Integer getBookId() {
        return this.bookId;
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "publisher_id")
    public Publisher getPublisher() {
        return this.publisher;
    }

    public void setPublisher(Publisher publishers) {
        this.publisher = publishers;
    }

    @Column(name = "title", nullable = false, length = 255)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "isbn", length = 20)
    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "published_date", length = 10)
    public Date getPublishedDate() {
        return this.publishedDate;
    }

    public void setPublishedDate(Date publishedDate) {
        this.publishedDate = publishedDate;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "book_authors", catalog = "bookdb", joinColumns = {
            @JoinColumn(name = "book_id", nullable = false) }, inverseJoinColumns = {
                    @JoinColumn(name = "author_id", nullable = false) })
    public Set<Author> getAuthors() {
        return this.authors;
    }

    public void setAuthors(Set<Author> authorses) {
        this.authors = authorses;
    }

    @Override
    public String toString() {
        return "Book [bookId=" + bookId + ", title=" + title + ", isbn=" + isbn + ", publishedDate=" + publishedDate
                + "]";
    }

    public void addAuthor(Author author) {
        this.getAuthors().add(author);
        author.getBooks().add(this);
    }

}
