package com.example.hibernate.model;
// Generated 30 ene 2025, 17:49:46 by Hibernate Tools 6.6.0.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MapsId;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * Contactinfo generated by hbm2java
 */
@Entity
@Table(name = "contactinfo", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class ContactInfo implements java.io.Serializable {

    private int profesorId;
    private Profesor profesor;
    private String email;
    private String tlfMovil;

    public ContactInfo() {
    }

    public ContactInfo(Profesor profesor, String email) {
        this.profesor = profesor;
        this.email = email;
    }

    public ContactInfo(Profesor profesor, String email, String tlfMovil) {
        this.profesor = profesor;
        this.email = email;
        this.tlfMovil = tlfMovil;
    }

    // @GenericGenerator(name="com.example.hibernate.model.ContactinfoIdGenerator",
    // strategy="foreign")@Id
    // @GeneratedValue(generator="com.example.hibernate.model.ContactinfoIdGenerator")

    
    // @GeneratedValue
    @Id
    @Column(name = "profesorId", unique = true, nullable = false)
    public int getProfesorId() {
        return this.profesorId;
    }

    public void setProfesorId(int profesorId) {
        this.profesorId = profesorId;
    }

    @MapsId
    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn(name="profesorId")
    public Profesor getProfesor() {
        return this.profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    @Column(name = "email", unique = true, nullable = false, length = 255)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "tlf_movil", length = 15)
    public String getTlfMovil() {
        return this.tlfMovil;
    }

    public void setTlfMovil(String tlfMovil) {
        this.tlfMovil = tlfMovil;
    }

}
