package com.example.hibernate.model;
// Generated 13 mar 2025, 20:02:05 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
)
public class Department  implements java.io.Serializable {


     private Integer deptno;
     private String dname;
     private String loc;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Department() {
    }

    public Department(String dname, String loc, Set<Employee> employees) {
       this.dname = dname;
       this.loc = loc;
       this.employees = employees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="DEPTNO", unique=true, nullable=false)
    public Integer getDeptno() {
        return this.deptno;
    }
    
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    
    @Column(name="DNAME", length=20)
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }

    
    @Column(name="LOC", length=20)
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


