package com.example.hibernate.model;
// Generated 20 feb 2025, 18:07:51 by Hibernate Tools 6.6.0.Final


import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name="project"
)
public class Project  implements java.io.Serializable {


     private Integer projno;
     private String projname;
     private Set<Empleado> emps = new HashSet<Empleado>(0);

    public Project() {
    }

	
    public Project(String projname) {
        this.projname = projname;
    }
    public Project(String projname, Set<Empleado> emps) {
       this.projname = projname;
       this.emps = emps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PROJNO", unique=true, nullable=false)
    public Integer getProjno() {
        return this.projno;
    }
    
    public void setProjno(Integer projno) {
        this.projno = projno;
    }

    
    @Column(name="PROJNAME", nullable=false, length=50)
    public String getProjname() {
        return this.projname;
    }
    
    public void setProjname(String projname) {
        this.projname = projname;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="projects")
    
    public Set<Empleado> getEmps() {
        return this.emps;
    }
    
    public void setEmps(Set<Empleado> emps) {
        this.emps = emps;
    }




}


