package com.example.hibernate.model;
// Generated 30 ene 2025, 17:49:46 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
)
public class Provincia  implements java.io.Serializable {


     private int idProvincia;
     private ComunidadAutonoma comunidadAutonoma;
     private String nombre;
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Provincia() {
    }

	
    public Provincia(int idProvincia, ComunidadAutonoma comunidadautonoma) {
        this.idProvincia = idProvincia;
        this.comunidadAutonoma = comunidadautonoma;
    }

    public Provincia(int idProvincia, ComunidadAutonoma comunidadautonoma, String nombre, Set<Direccion> direccions) {
        this.idProvincia = idProvincia;
        this.comunidadAutonoma = comunidadautonoma;
        this.nombre = nombre;
        this.direccions = direccions;
    }
    
     
    public Provincia(int idProvincia, ComunidadAutonoma comunidadautonoma, String nombre) {
        this.idProvincia = idProvincia;
        this.comunidadAutonoma = comunidadautonoma;
        this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="idProvincia", unique=true, nullable=false)
    public int getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCA", nullable=false)
    public ComunidadAutonoma getComunidadAutonoma() {
        return this.comunidadAutonoma;
    }
    
    public void setComunidadAutonoma(ComunidadAutonoma comunidadautonoma) {
        this.comunidadAutonoma = comunidadautonoma;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provincia")
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


