package com.example.hibernate.model;
// Generated 5 jun 2025, 5:59:52 by Hibernate Tools 6.6.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Publishers generated by hbm2java
 */
@Entity
@Table(name="publishers"
)
public class Publisher  implements java.io.Serializable {


     private Integer publisherId;
     private String name;
     private Set<Book> books = new HashSet<Book>(0);

    public Publisher() {
    }

	
    public Publisher(String name) {
        this.name = name;
    }
    public Publisher(String name, Set<Book> bookses) {
       this.name = name;
       this.books = bookses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="publisher_id", unique=true, nullable=false)
    public Integer getPublisherId() {
        return this.publisherId;
    }
    
    public void setPublisherId(Integer publisherId) {
        this.publisherId = publisherId;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="publisher")
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> bookses) {
        this.books = bookses;
    }




}


